export default {

    COMMON_PUSH_PATH: 'COMMON_PUSH_PATH',

    LOGIN_USERNAME_CHANGE: 'LOGIN_USERNAME_CHANGE',
    LOGIN_PASSWORD_CHANGE: 'LOGIN_PASSWORD_CHANGE',
    LOGIN_SET_LOADING: 'LOGIN_SET_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_SET_ERROR: 'LOGIN_SET_ERROR',
    LOGIN_DO_LOGOUT: 'LOGIN_DO_LOGOUT',
    LOGIN_DO_LOGIN: 'LOGIN_DO_LOGIN',
    LOGIN_DESTROY: 'LOGIN_DESTROY',

    ADD_TASK: 'ADD_TASK',

    PLANET_LIST_SET_PLANETS: 'PLANET_LIST_SET_PLANETS',
    PLANET_LIST_SET_LOADING: 'PLANET_LIST_SET_LOADING',
    PLANET_LIST_SET_ERROR: 'PLANET_LIST_SET_ERROR',
    PLANET_LIST_DESTROY: 'PLANET_LIST_DESTROY',
    PLANET_LIST_FETCH_PLANETS: 'PLANET_LIST_FETCH_PLANETS',
    
    PRODUCT_LIST_SET_PRODUCTS: 'PRODUCT_LIST_SET_PRODUCTS',
    PRODUCT_LIST_SET_LOADING: 'PRODUCT_LIST_SET_LOADING',
    PRODUCT_LIST_SET_ERROR: 'PRODUCT_LIST_SET_ERROR',
    PRODUCT_LIST_DESTROY: 'PRODUCT_LIST_DESTROY',
    PRODUCT_LIST_FETCH_PRODUCTS: 'PRODUCT_LIST_FETCH_PRODUCTS',

    CATEGORY_LIST_SET_CATEGORIES: 'CATEGORY_LIST_SET_CATEGORIES',
    CATEGORY_LIST_SET_LOADING: 'CATEGORY_LIST_SET_LOADING',
    CATEGORY_LIST_SET_ERROR: 'CATEGORY_LIST_SET_ERROR',
    CATEGORY_LIST_DESTROY: 'CATEGORY_LIST_DESTROY',
    CATEGORY_LIST_FETCH_CATEGORIES: 'CATEGORY_LIST_FETCH_CATEGORIES',

    PLANET_DETAIL_SET_LOADING: 'PLANET_DETAIL_SET_LOADING',
    PLANET_DETAIL_SET_ERROR: 'PLANET_DETAIL_SET_ERROR',
    PLANET_DETAIL_DESTROY: 'PLANET_DETAIL_DESTROY',
    PLANET_DETAIL_SET_PLANET_DETAILS: 'PLANET_DETAIL_SET_PLANET_DETAILS',
    PLANET_DETAIL_FETCH_PLANET_DETAILS: 'PLANET_DETAIL_FETCH_PLANET_DETAILS'


}
