export default {
    LOGIN_USERNAME_CHANGE: 'LOGIN_USERNAME_CHANGE',
    LOGIN_PASSWORD_CHANGE: 'LOGIN_PASSWORD_CHANGE',
    LOGIN_SET_LOADING: 'LOGIN_SET_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_SET_ERROR: 'LOGIN_SET_ERROR',
    LOGIN_DO_LOGOUT: 'LOGIN_DO_LOGOUT',
    LOGIN_DO_LOGIN: 'LOGIN_DO_LOGIN',
    LOGIN_DESTROY: 'LOGIN_DESTROY',
    ADD_TASK: 'ADD_TASK',

}
